import type { PrismaClient } from "@prisma/client";
import { novu as novuClient } from "@gql-prisma-api/utils/novu.js";
import { NovuService } from "@gql-prisma-api/modules/novu/service.js";
import { AddressService } from "@gql-prisma-api/modules/address/service.js";
import { AuthService } from "@gql-prisma-api/modules/auth/service.js";
import { BlogService } from "@gql-prisma-api/modules/blog/service.js";
import { CartService } from "@gql-prisma-api/modules/cart/service.js";
import { ConversationService } from "@gql-prisma-api/modules/conversation/service.js";
import { CouponService } from "@gql-prisma-api/modules/coupon/service.js";
import { DiscountService } from "@gql-prisma-api/modules/discount/service.js";
import { FollowService } from "@gql-prisma-api/modules/follow/service.js";
import { InvoiceService } from "@gql-prisma-api/modules/invoice/service.js";
import { NotificationService } from "@gql-prisma-api/modules/notification/service.js";
import { OrderService } from "@gql-prisma-api/modules/order/service.js";
import { PaymentService } from "@gql-prisma-api/modules/payment/service.js";
import { PostViewService } from "@gql-prisma-api/modules/postView/service.js";
import { ProductService } from "@gql-prisma-api/modules/product/service.js";
import { ProductImageService } from "@gql-prisma-api/modules/productImage/service.js";
import { RefundService } from "@gql-prisma-api/modules/refund/service.js";
import { ReturnService } from "@gql-prisma-api/modules/return/service.js";
import { ReviewService } from "@gql-prisma-api/modules/review/service.js";
import { SavedPostService } from "@gql-prisma-api/modules/savedPost/service.js";
import { ShipmentService } from "@gql-prisma-api/modules/shipment/service.js";
import { StatsService } from "@gql-prisma-api/modules/stats/service.js";
import { SubscriptionService } from "@gql-prisma-api/modules/subscription/service.js";
import { SupportService } from "@gql-prisma-api/modules/support/service.js";
import { UserService } from "@gql-prisma-api/modules/user/service.js";
import { WishlistService } from "@gql-prisma-api/modules/wishlist/service.js";

export class Services {
  readonly address: AddressService;
  readonly auth: AuthService;
  readonly blog: BlogService;
  readonly cart: CartService;
  readonly conversation: ConversationService;
  readonly coupon: CouponService;
  readonly discount: DiscountService;
  readonly follow: FollowService;
  readonly invoice: InvoiceService;
  readonly notification: NotificationService;
  readonly novu: NovuService;
  readonly order: OrderService;
  readonly payment: PaymentService;
  readonly postView: PostViewService;
  readonly product: ProductService;
  readonly productImage: ProductImageService;
  readonly refund: RefundService;
  readonly return: ReturnService;
  readonly review: ReviewService;
  readonly savedPost: SavedPostService;
  readonly shipment: ShipmentService;
  readonly stats: StatsService;
  readonly subscription: SubscriptionService;
  readonly support: SupportService;
  readonly user: UserService;
  readonly wishlist: WishlistService;

  constructor(prisma: PrismaClient) {
    this.address = new AddressService(prisma);
    this.auth = new AuthService(prisma);
    this.blog = new BlogService(prisma);
    this.cart = new CartService(prisma);
    this.conversation = new ConversationService(prisma);
    this.coupon = new CouponService(prisma);
    this.discount = new DiscountService(prisma);
    this.follow = new FollowService(prisma);
    this.invoice = new InvoiceService(prisma);
    this.notification = new NotificationService(prisma);
    this.novu = new NovuService(prisma, novuClient);
    this.order = new OrderService(prisma);
    this.payment = new PaymentService(prisma);
    this.postView = new PostViewService(prisma);
    this.product = new ProductService(prisma);
    this.productImage = new ProductImageService(prisma);
    this.refund = new RefundService(prisma);
    this.return = new ReturnService(prisma);
    this.review = new ReviewService(prisma);
    this.savedPost = new SavedPostService(prisma);
    this.shipment = new ShipmentService(prisma);
    this.stats = new StatsService(prisma);
    this.subscription = new SubscriptionService(prisma);
    this.support = new SupportService(prisma);
    this.user = new UserService(prisma);
    this.wishlist = new WishlistService(prisma);
  }
}
