import type { PrismaClient } from "@prisma/client";
import { BaseService } from "./BaseService.js";
import { AddressService } from "../modules/address/service.js";
import { AuthService } from "../modules/auth/service.js";
import { BlogService } from "../modules/blog/service.js";
import { CartService } from "../modules/cart/service.js";
import { ConversationService } from "../modules/conversation/service.js";
import { CouponService } from "../modules/coupon/service.js";
import { DiscountService } from "../modules/discount/service.js";
import { FollowService } from "../modules/follow/service.js";
import { InvoiceService } from "../modules/invoice/service.js";
import { NotificationService } from "../modules/notification/service.js";
import { OrderService } from "../modules/order/service.js";
import { PaymentService } from "../modules/payment/service.js";
import { PostViewService } from "../modules/postView/service.js";
import { ProductService } from "../modules/product/service.js";
import { ProductImageService } from "../modules/productImage/service.js";
import { RefundService } from "../modules/refund/service.js";
import { ReturnService } from "../modules/return/service.js";
import { ReviewService } from "../modules/review/service.js";
import { SavedPostService } from "../modules/savedPost/service.js";
import { ShipmentService } from "../modules/shipment/service.js";
import { StatsService } from "../modules/stats/service.js";
import { SubscriptionService } from "../modules/subscription/service.js";
import { SupportService } from "../modules/support/service.js";
import { UserService } from "../modules/user/service.js";
import { WishlistService } from "../modules/wishlist/service.js";

export class Services {
  readonly address: AddressService;
  readonly auth: AuthService;
  readonly blog: BlogService;
  readonly cart: CartService;
  readonly conversation: ConversationService;
  readonly coupon: CouponService;
  readonly discount: DiscountService;
  readonly follow: FollowService;
  readonly invoice: InvoiceService;
  readonly notification: NotificationService;
  readonly order: OrderService;
  readonly payment: PaymentService;
  readonly postView: PostViewService;
  readonly product: ProductService;
  readonly productImage: ProductImageService;
  readonly refund: RefundService;
  readonly return: ReturnService;
  readonly review: ReviewService;
  readonly savedPost: SavedPostService;
  readonly shipment: ShipmentService;
  readonly stats: StatsService;
  readonly subscription: SubscriptionService;
  readonly support: SupportService;
  readonly user: UserService;
  readonly wishlist: WishlistService;

  constructor(prisma: PrismaClient) {
    const base = new BaseService(prisma);
    this.address = new AddressService(base);
    this.auth = new AuthService(base);
    this.blog = new BlogService(base);
    this.cart = new CartService(base);
    this.conversation = new ConversationService(base);
    this.coupon = new CouponService(base);
    this.discount = new DiscountService(base);
    this.follow = new FollowService(base);
    this.invoice = new InvoiceService(base);
    this.notification = new NotificationService(base);
    this.order = new OrderService(base);
    this.payment = new PaymentService(base);
    this.postView = new PostViewService(base);
    this.product = new ProductService(base);
    this.productImage = new ProductImageService(base);
    this.refund = new RefundService(base);
    this.return = new ReturnService(base);
    this.review = new ReviewService(base);
    this.savedPost = new SavedPostService(base);
    this.shipment = new ShipmentService(base);
    this.stats = new StatsService(base);
    this.subscription = new SubscriptionService(base);
    this.support = new SupportService(base);
    this.user = new UserService(base);
    this.wishlist = new WishlistService(base);
  }
}
