import type { PrismaClient } from "@prisma/client";
import { BaseService } from "@gql-prisma-api/lib/BaseService.js";

export class StatsService extends BaseService {
  async getStats() {
    const [
      totalUsers,
      totalPosts,
      totalPublishedPosts,
      totalTags,
      totalCategories,
      totalComments,
      totalLikes,
      totalProducts,
      totalOrders,
      totalPayments,
      totalRefunds,
      totalReviews,
      totalAddresses,
      totalWishlists,
      totalCarts,
      totalCoupons,
      totalShipments,
      totalNotifications,
      totalFollows,
      totalSavedPosts,
      totalPostViews,
    ] = await Promise.all([
      this.core.user.count(),
      this.core.post.count(),
      this.core.post.count({ where: { published: true } }),
      this.core.tag.count(),
      this.core.category.count(),
      this.core.comment.count(),
      this.core.like.count(),
      this.core.product.count(),
      this.core.order.count(),
      this.core.payment.count(),
      this.core.refund.count(),
      this.core.review.count(),
      this.core.address.count(),
      this.core.wishlist.count(),
      this.core.cart.count(),
      this.core.coupon.count(),
      this.core.shipment.count(),
      this.core.notification.count(),
      this.core.follow.count(),
      this.core.savedPost.count(),
      this.core.postView.count(),
    ]);
    return {
      totalUsers,
      totalPosts,
      totalPublishedPosts,
      totalTags,
      totalCategories,
      totalComments,
      totalLikes,
      totalProducts,
      totalOrders,
      totalPayments,
      totalRefunds,
      totalReviews,
      totalAddresses,
      totalWishlists,
      totalCarts,
      totalCoupons,
      totalShipments,
      totalNotifications,
      totalFollows,
      totalSavedPosts,
      totalPostViews,
    };
  }
}
