export enum Role {
  USER = "USER",
  ADMIN = "ADMIN",
  MODERATOR = "MODERATOR",
}

export enum OrderStatus {
  PENDING = "PENDING",
  CONFIRMED = "CONFIRMED",
  PROCESSING = "PROCESSING",
  SHIPPED = "SHIPPED",
  DELIVERED = "DELIVERED",
  CANCELLED = "CANCELLED",
}

export enum PaymentMethod {
  CREDIT_CARD = "CREDIT_CARD",
  DEBIT_CARD = "DEBIT_CARD",
  PAYPAL = "PAYPAL",
  BANK_TRANSFER = "BANK_TRANSFER",
  CASH_ON_DELIVERY = "CASH_ON_DELIVERY",
}

export enum PaymentStatus {
  PENDING = "PENDING",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED",
  REFUNDED = "REFUNDED",
}

export enum RefundStatus {
  PENDING = "PENDING",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
  COMPLETED = "COMPLETED",
}

export enum ShipmentStatus {
  PENDING = "PENDING",
  PICKED_UP = "PICKED_UP",
  IN_TRANSIT = "IN_TRANSIT",
  OUT_FOR_DELIVERY = "OUT_FOR_DELIVERY",
  DELIVERED = "DELIVERED",
  FAILED = "FAILED",
}

export enum NotificationType {
  SYSTEM = "SYSTEM",
  ORDER_UPDATE = "ORDER_UPDATE",
  PAYMENT_RECEIVED = "PAYMENT_RECEIVED",
  SHIPMENT_UPDATE = "SHIPMENT_UPDATE",
  NEW_FOLLOWER = "NEW_FOLLOWER",
  NEW_COMMENT = "NEW_COMMENT",
  NEW_LIKE = "NEW_LIKE",
  REVIEW_REPLY = "REVIEW_REPLY",
  PROMOTION = "PROMOTION",
  NEW_MESSAGE = "NEW_MESSAGE",
  SUBSCRIPTION_EXPIRING = "SUBSCRIPTION_EXPIRING",
  DISCOUNT_AVAILABLE = "DISCOUNT_AVAILABLE",
  INVOICE_CREATED = "INVOICE_CREATED",
  INVOICE_PAID = "INVOICE_PAID",
  INVOICE_OVERDUE = "INVOICE_OVERDUE",
  RETURN_REQUESTED = "RETURN_REQUESTED",
  RETURN_APPROVED = "RETURN_APPROVED",
  RETURN_REJECTED = "RETURN_REJECTED",
  RETURN_REFUNDED = "RETURN_REFUNDED",
  TICKET_CREATED = "TICKET_CREATED",
  TICKET_UPDATED = "TICKET_UPDATED",
  TICKET_RESOLVED = "TICKET_RESOLVED",
}
